location / {
    try_files $uri $uri/ /index.php$is_args$query_string;
}

location ~ \.php$ {
    fastcgi_pass ${NGINX_PHP_FPM};
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
}

# Static files
location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
}
